"""phase2 outbox table

Revision ID: 6249f56c26a5
Revises: 88ba19ac2488
Create Date: 2026-09-09 06:32:27.398705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6249f56c26a5'
down_revision: Union[str, Sequence[str], None] = '88ba19ac2488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('jira_result_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_state'))
        batch_op.drop_index(batch_op.f('ix_outbox_session_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_next_attempt_at'))

    op.drop_table('outbox')
    # ### end Alembic commands ###
