"""phase1 initial schema: boards issues sessions settings

Revision ID: 88ba19ac2488
Revises: 
Create Date: 2026-09-09 03:07:48.193338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ba19ac2488'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_base_url', sa.String(), nullable=True),
    sa.Column('jira_email', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=False),
    sa.Column('ollama_url', sa.String(), nullable=True),
    sa.Column('ollama_model', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('nudge_time', sa.String(), nullable=True),
    sa.Column('idle_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('default_transition', sa.String(), nullable=True),
    sa.Column('uses_tempo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jira_id', sa.String(), nullable=False),
    sa.Column('issue_key', sa.String(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('parent_key', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_category', sa.String(), nullable=True),
    sa.Column('assignee_account_id', sa.String(), nullable=True),
    sa.Column('sprint_name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', sa.BLOB(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_issue_key'), ['issue_key'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('issue_key', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_seconds', sa.Integer(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adjusted_seconds', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('issue_origin', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('worklog_jira_id', sa.String(), nullable=True),
    sa.Column('comment_jira_id', sa.String(), nullable=True),
    sa.Column('sync_state', sa.String(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_issue_key'))
        batch_op.drop_index(batch_op.f('ix_issues_board_id'))

    op.drop_table('issues')
    op.drop_table('settings')
    op.drop_table('boards')
    # ### end Alembic commands ###
